feeds:
  - name: "The Block"
    url: "https://www.theblock.co/post/rss"
  - name: "CoinDesk"
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/"
  - name: "Cointelegraph"
    url: "https://cointelegraph.com/rss"
